### ISSUE TITLE
files.addFile appends api prefix twice

### ISSUE THREAD

**Issue by sanderpick** [textileio/js-http-client#60]
`POST http://127.0.0.1:41600/api/v0/api/v0/threads/12D3KooWR6CjYPeutcj1wa32vhSYUiZkjLvXdDWtiEXXBEnjudP3/files 404 (Not Found)`

**Comment by sanderpick** [comment]
This seems to occur only in browser builds. (I see it after webpacking the /dist folder) on master.

**Comment by andrewxhill** [comment]
yeah... hmm. thought i fixed that here https://github.com/textileio/js-http-client/pull/59

**Comment by sanderpick** [comment]
Have you tried it in the browser? Still seeing it over here.

**Comment by andrewxhill** [comment]
running it like

`webpack-dev-server  --mode development --inline --hot --open`

on my branch from last night works fine. i can try master here now and make sure the build was the same i guess...

**Comment by andrewxhill** [comment]
seems to work with that run mode and `^0.2.10`

**Comment by sanderpick** [comment]
Ok, good deal
